[phases.install]
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
cmds = ["npx prisma generate --schema ./prisma/schema.prisma", "cd backend && npm run build"]

[start]
cmd = "node backend/dist/server.js"
